spring.application.name=Car Rent Management Gateway
server.port=8762
eureka.client.service-url.default-zone=http://localhost:8761/eureka/
# A prefix that can added to beginning of all requests.
zuul.prefix=/api/v1
# They should be only accessed through the path defined below.
zuul.ignored-services=*
# Map paths to services
zuul.routes.auth-service.path=/auth/**
zuul.routes.auth-service.service-id=auth-service
zuul.routes.user-service.path=/user/**
zuul.routes.user-service.service-id=user-service
zuul.routes.car-service.path=/car/**
zuul.routes.car-service.service-id=car-service
zuul.routes.contract-service.path=/contract/**
zuul.routes.contract-service.service-id=contract-service

